### PR TITLE
Add repositories for providing builds of rperf and NetBird.

### PR DESCRIPTION
**Pull request by mbfm**
We would like to provide builds of [`rperf`](https://github.com/opensource-3d-p/rperf) and [NetBird](https://netbird.io) akin to `cannelloni` in a separate repository, to avoid any licensing issues that might arise from compiling it within the `opendut` repository.

### CODE REVIEW

**Review by netomi — DISMISSED** [review]
LGTM, happy to merge once a PL approves

**Comment by mbfm** [comment]
Hey @netomi, I added another commit, as we'd like to go to one of the project leads and get all this approved at once. It seemed easier to coordinate this way than opening another pull request.

**Comment by netomi** [comment]
sure np, once a PL approves you can merge yourself, I do not need to intervene.

**Review by Ovomaltine85 — APPROVED** [review]
thank you and cheers

**Comment by netomi** [comment]
looking into the problem with creating the fork, something must have changed on GitHub side.

**Comment by netomi** [comment]
its fixed, the format of the forked repo was wrong, you need to specify the repo as <owner>/<repo> instead of an URL.

Should add a validation for that, did not see it myself.

**Comment by netomi** [comment]
added validation for the forked_repository parameter in https://github.com/eclipse-csi/otterdog/commit/c02f2097d7ff04b050f2fbf751ce029c39d1aae6

**Pull request merged**
